"""outbox unique (aggregate_id, target_adapter)

Revision ID: 5e02a22c07a2
Revises: f4a969e1716f
Create Date: 2026-06-18 11:14:29.938980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e02a22c07a2'
down_revision: Union[str, Sequence[str], None] = 'f4a969e1716f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_outbox_aggregate_target', 'outbox', ['aggregate_id', 'target_adapter'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_outbox_aggregate_target', 'outbox', type_='unique')
    # ### end Alembic commands ###
