"""initial schema (skeleton tables)

Revision ID: f4a969e1716f
Revises: 
Create Date: 2026-06-18 01:00:55.118592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a969e1716f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('scope_used', sa.String(length=100), nullable=True),
    sa.Column('result_status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_audit_log_timestamp'), 'mcp_audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_mcp_audit_log_tool_name'), 'mcp_audit_log', ['tool_name'], unique=False)
    op.create_index(op.f('ix_mcp_audit_log_user_id'), 'mcp_audit_log', ['user_id'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider')
    )
    op.create_table('orders',
    sa.Column('internal_id', sa.Integer(), nullable=False),
    sa.Column('odoo_order_id', sa.Integer(), nullable=True),
    sa.Column('marketplace', sa.String(length=50), nullable=False),
    sa.Column('marketplace_order_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('internal_id'),
    sa.UniqueConstraint('marketplace', 'marketplace_order_id', name='uq_orders_marketplace_id')
    )
    op.create_index(op.f('ix_orders_marketplace_order_id'), 'orders', ['marketplace_order_id'], unique=False)
    op.create_index(op.f('ix_orders_odoo_order_id'), 'orders', ['odoo_order_id'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_id', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('target_adapter', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_aggregate_id'), 'outbox', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_next_attempt_at'), 'outbox', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_outbox_status'), 'outbox', ['status'], unique=False)
    op.create_table('webhook_dedup',
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('source', 'event_id')
    )
    op.create_table('webhook_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_body', sa.JSON(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_log_event_id'), 'webhook_log', ['event_id'], unique=False)
    op.create_index(op.f('ix_webhook_log_source'), 'webhook_log', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_log_source'), table_name='webhook_log')
    op.drop_index(op.f('ix_webhook_log_event_id'), table_name='webhook_log')
    op.drop_table('webhook_log')
    op.drop_table('webhook_dedup')
    op.drop_index(op.f('ix_outbox_status'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_next_attempt_at'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_aggregate_id'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_orders_odoo_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_marketplace_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_mcp_audit_log_user_id'), table_name='mcp_audit_log')
    op.drop_index(op.f('ix_mcp_audit_log_tool_name'), table_name='mcp_audit_log')
    op.drop_index(op.f('ix_mcp_audit_log_timestamp'), table_name='mcp_audit_log')
    op.drop_table('mcp_audit_log')
    # ### end Alembic commands ###
